//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Drone
{
    [Serializable]
    public class WinchControlMsg : Message
    {
        public const string k_RosMessageName = "drone_msgs/WinchControl";
        public override string RosMessageName => k_RosMessageName;

        public float target_length;
        public float winch_speed;

        public WinchControlMsg()
        {
            this.target_length = 0.0f;
            this.winch_speed = 0.0f;
        }

        public WinchControlMsg(float target_length, float winch_speed)
        {
            this.target_length = target_length;
            this.winch_speed = winch_speed;
        }

        public static WinchControlMsg Deserialize(MessageDeserializer deserializer) => new WinchControlMsg(deserializer);

        private WinchControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_length);
            deserializer.Read(out this.winch_speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_length);
            serializer.Write(this.winch_speed);
        }

        public override string ToString()
        {
            return "WinchControlMsg: " +
            "\ntarget_length: " + target_length.ToString() +
            "\nwinch_speed: " + winch_speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
